EmployeeInfo/Controllers/AssignmentMarchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeInfo.Data;
using EmployeeInfo.Data.Entity;
using EmployeeInfo.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeInfo.Controllers
{
    public class AssignmentMarchController : Controller
    {
        private readonly SBLDbContext _context;
        public AssignmentMarchController(SBLDbContext _context)
        {
            this._context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(AssignmentMrachViewModel model)
        {
            AssignmentMarch customer = new AssignmentMarch
            {
                FristName = model.FristName,
                LesttName = model.LesttName,
                Email = model.Email,
                Subject = model.Subject,
                Massage = model.Massage,
            };
            _context.AssignmentMarchs.Add(customer);
            await _context.SaveChangesAsync();

            return View();
           
        }

        [HttpPost]
        public async Task<IActionResult> IndexSaveByAjaxFun(AssignmentMrachViewModel model)
        {
            string msg = "error";
            try
            {
                AssignmentMarch customer = new AssignmentMarch
                {
                    FristName = model.FristName,
                    LesttName = model.LesttName,
                    Email = model.Email,
                    Subject = model.Subject,
                    Massage = model.Massage,
                };
                _context.AssignmentMarchs.Add(customer);
                await _context.SaveChangesAsync();
                msg = "success";

            }
            catch (Exception e)
            {
                msg = "error";
                //throw e;
            }

            return Json(msg);

        }

    }
}

EmployeeInfo/Controllers/BusTicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeInfo.Data;
using EmployeeInfo.Data.Entity;
using EmployeeInfo.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeInfo.Controllers
{
    public class BusTicketController : Controller
    {
        private readonly SBLDbContext _context;
        public BusTicketController(SBLDbContext _context)
        {
            this._context = _context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(BusTicketViewModel model)
        {
            try
            {
                BusTicket customer = new BusTicket
                {
                    pname = model.pname,
                    paddress = model.paddress,
                    form = model.form,
                    to = model.to,
                    sitno = model.sitno,
                    amount = model.amount,
                    comment = model.comment,
                };
                _context.BusTickets.Add(customer);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw e;
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> IndexSaveByAjaxFun(BusTicketViewModel model)
        {
            string msg = "error";
            try
            {
                BusTicket customer = new BusTicket
                {
                    pname = model.pname,
                    paddress = model.paddress,
                    form = model.form,
                    to = model.to,
                    sitno = model.sitno,
                    amount = model.amount,
                    comment = model.comment,
                };
                _context.BusTickets.Add(customer);
                await _context.SaveChangesAsync();
                msg = "success";
            }
            catch (Exception e)
            {
                msg = "error";
            }

            return Json(msg);
        }
    }
}

EmployeeInfo/Controllers/SBLCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeInfo.Data;
using EmployeeInfo.Data.Entity;
using EmployeeInfo.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeInfo.Controllers
{
    public class SBLCardController : Controller
    {
        private readonly SBLDbContext _context;
        public SBLCardController(SBLDbContext _context)
        {
            this._context = _context;
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MordernDesign()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MordernDesign(SBLViewModel model)
        {
            
            CustomerRequsition customer = new CustomerRequsition
            {
                date =  model.date,
                requsetFor = model.requsetFor,
                addressType =  model.addressType,
                houseName =  model.houseName,
                designation = model.designation,
                house = model.house,
                flat = model.flat,
                floor = model.floor,
                road = model.road,
                village = model.village,
                thana = model.thana,
                district = model.district,
                mobileHome = model.mobileHome,
                mobileOffice = model.mobileOffice,
                mobile = model.mobile,
                creaditCard = model.creaditCard,
                lostCard = model.lostCard,
                closeCreditCardReason = model.closeCreditCardReason,
                IssueANewPIN = model.IssueANewPIN,
                LostChequeBookForm = model.LostChequeBookForm,
                LostChequeBookTo = model.LostChequeBookTo,
                LostChequeBookFor = model.LostChequeBookFor,
                LosUpdateDocument = model.LosUpdateDocument,
                Nid = model.Nid,
                Password = model.Password,
                etin = model.etin,
                LimitConversation = model.LimitConversation,
                formBDT = model.formBDT,
                toUSD = model.toUSD,
                formUSD = model.formUSD,
                toBDT = model.toBDT,
                AutoDebitInstruction = model.AutoDebitInstruction,
                accountNo = model.accountNo,
                BranchName = model.BranchName,
                AmountBDT_USD = model.AmountBDT_USD,
                EnhanceLimitCreditCard = model.EnhanceLimitCreditCard,
                BDT = model.BDT,
                Inword = model.Inword,
                Waive = model.Waive,
                Reason = model.Reason,
                signature = model.signature,
                NewSignature = model.NewSignature,
                OldSignature = model.OldSignature,
                ChangeEmail = model.ChangeEmail,
                FormMonthe = model.FormMonthe,
                ToMonth = model.ToMonth,
                certificate = model.certificate,
                service = model.service,
                others = model.others

            };

            _context.CustomerRequsitions.Add(customer);
            await _context.SaveChangesAsync();
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MordernDesign2(SBLViewModel model)
        {

            CustomerRequsition customer = new CustomerRequsition
            {
                date = model.date,
                requsetFor = model.requsetFor,
                addressType = model.addressType,
                houseName = model.houseName,
                designation = model.designation,
                house = model.house,
                flat = model.flat,
                floor = model.floor,
                road = model.road,
                village = model.village,
                thana = model.thana,
                district = model.district,
                mobileHome = model.mobileHome,
                mobileOffice = model.mobileOffice,
                mobile = model.mobile,
                creaditCard = model.creaditCard,
                lostCard = model.lostCard,
                closeCreditCardReason = model.closeCreditCardReason,
                IssueANewPIN = model.IssueANewPIN,
                LostChequeBookForm = model.LostChequeBookForm,
                LostChequeBookTo = model.LostChequeBookTo,
                LostChequeBookFor = model.LostChequeBookFor,
                LosUpdateDocument = model.LosUpdateDocument,
                Nid = model.Nid,
                Password = model.Password,
                etin = model.etin,
                LimitConversation = model.LimitConversation,
                formBDT = model.formBDT,
                toUSD = model.toUSD,
                formUSD = model.formUSD,
                toBDT = model.toBDT,
                AutoDebitInstruction = model.AutoDebitInstruction,
                accountNo = model.accountNo,
                BranchName = model.BranchName,
                AmountBDT_USD = model.AmountBDT_USD,
                EnhanceLimitCreditCard = model.EnhanceLimitCreditCard,
                BDT = model.BDT,
                Inword = model.Inword,
                Waive = model.Waive,
                Reason = model.Reason,
                signature = model.signature,
                NewSignature = model.NewSignature,
                OldSignature = model.OldSignature,
                ChangeEmail = model.ChangeEmail,
                FormMonthe = model.FormMonthe,
                ToMonth = model.ToMonth,
                certificate = model.certificate,
                service = model.service,
                others = model.others

            };

            _context.CustomerRequsitions.Add(customer);
            await _context.SaveChangesAsync();

            return View("MordernDesign");
            //return RedirectToAction("MordernDesign", "SBLCard");
        }


        [HttpPost]
        public async Task<IActionResult> AjaxSave(SBLViewModel model)
        {
            string msg = "error";

            try
            {
                CustomerRequsition customer = new CustomerRequsition
                {
                    date = model.date,
                    requsetFor = model.requsetFor,
                    addressType = model.addressType,
                    houseName = model.houseName,
                    designation = model.designation,
                    house = model.house,
                    flat = model.flat,
                    floor = model.floor,
                    road = model.road,
                    village = model.village,
                    thana = model.thana,
                    district = model.district,
                    mobileHome = model.mobileHome,
                    mobileOffice = model.mobileOffice,
                    mobile = model.mobile,
                    creaditCard = model.creaditCard,
                    lostCard = model.lostCard,
                    closeCreditCardReason = model.closeCreditCardReason,
                    IssueANewPIN = model.IssueANewPIN,
                    LostChequeBookForm = model.LostChequeBookForm,
                    LostChequeBookTo = model.LostChequeBookTo,
                    LostChequeBookFor = model.LostChequeBookFor,
                    LosUpdateDocument = model.LosUpdateDocument,
                    Nid = model.Nid,
                    Password = model.Password,
                    etin = model.etin,
                    LimitConversation = model.LimitConversation,
                    formBDT = model.formBDT,
                    toUSD = model.toUSD,
                    formUSD = model.formUSD,
                    toBDT = model.toBDT,
                    AutoDebitInstruction = model.AutoDebitInstruction,
                    accountNo = model.accountNo,
                    BranchName = model.BranchName,
                    AmountBDT_USD = model.AmountBDT_USD,
                    EnhanceLimitCreditCard = model.EnhanceLimitCreditCard,
                    BDT = model.BDT,
                    Inword = model.Inword,
                    Waive = model.Waive,
                    Reason = model.Reason,
                    signature = model.signature,
                    NewSignature = model.NewSignature,
                    OldSignature = model.OldSignature,
                    ChangeEmail = model.ChangeEmail,
                    FormMonthe = model.FormMonthe,
                    ToMonth = model.ToMonth,
                    certificate = model.certificate,
                    service = model.service,
                    others = model.others

                };

                _context.CustomerRequsitions.Add(customer);
                await _context.SaveChangesAsync();

                msg = "success";
            }
            catch (Exception e)
            {
                msg = "error";
            }

            return Json(msg);
            //return RedirectToAction("MordernDesign", "SBLCard");
        }

    }
}

EmployeeInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeInfo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>


    @*dropdown with search*@
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />*@

    <link href="~/CustomSelectOption/select2.min.css" rel="stylesheet" />

    <link href="~/SweetAlert/sweetalert2.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    @*<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">*@

    <!-- Custom Date Picker-->
    @*<link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet" type="text/css" />*@

    <!-- Custom styles for this page -->

    <link href="~/data_table_offline_script/dataTables.bootstrap4.min.css" rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

    @*loading bar*@
    <link href="~/loading-bar/dist/loading-bar.css" rel="stylesheet" />

    <!-- Custom styles for this page -->
    <link href="~/css/jqueryui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">*@

    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" rel="stylesheet" />*@
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">*@

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeInfo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SBLCard" asp-action="Index">SBLCard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SBLCard" asp-action="MordernDesign">MordernDesign</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AssignmentMarch" asp-action="Index">AssignmentMarch</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusTicket" asp-action="Index">BusTicket</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeeInfo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Page level plugins -->

    <script src="~/data_table_offline_script/jquery.dataTables.min.js"></script>
    <script src="~/data_table_offline_script/dataTables.bootstrap4.min.js"></script>
    <script src="~/data_table_offline_script/dataTables.buttons.min.js"></script>
    <script src="~/data_table_offline_script/jszip.min.js"></script>
    <script src="~/data_table_offline_script/pdfmake.min.js"></script>
    <script src="~/data_table_offline_script/vfs_fonts.js"></script>
    <script src="~/data_table_offline_script/buttons.html5.min.js"></script>
    <script src="~/data_table_offline_script/buttons.print.min.js"></script>


    @*dropdown with search*@

    <script src="~/CustomSelectOption/select2.min.js"></script>

    <!-- Custom scripts for all autocomplete-->
    <script src="~/js/jquery.autocomplete.js" type="text/javascript"></script>

    @*loading bar*@
    <script src="~/loading-bar/dist/loading-bar.js"></script>

    <!-- Custom Date Picker-->
    @*<script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js" type="text/javascript"></script>*@

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- parsly Validation -->
    <script src="~/js/parsly.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>*@

    @*<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>*@

    <script src="~/SweetAlert/sweetalert2.common.js"></script>
    <script src="~/SweetAlert/sweetalert2.js"></script>
    <script src="~/js/jquery.autocomplete.js" type="text/javascript"></script>

    <script type="text/javascript" src="~/js/canvas/jquery.canvasjs.min.js"></script>

    <!-- Comon Ajax Lib -->
    <script type="text/javascript" src="~/js/common.js"></script>
    <script type="text/javascript" src="~/js/jquery.number.js"></script>
    <script type="text/javascript" src="~/js/jquery.number.min.js"></script>

    <script src="~/js/lay/poppermin.js"></script>
    <script src="~/js/lay/jquery-migrate-300min.js"></script>
    <script src="~/js/lay/bootstrapmin.js"></script>
    <script src="~/js/lay/jqueryui.js"></script>
    <script type="text/javascript" src="~/js/common.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>